[toolchain]
anchor_version = "0.26.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
doge_presale = "8GQ6CBmSHELjpfTFNRpo4SyqfvPfCmh7DXnxEhKiNQN6"

[programs.devnet]
doge_presale = "8GQ6CBmSHELjpfTFNRpo4SyqfvPfCmh7DXnxEhKiNQN6"

[programs.mainnet]
doge_presale = "8GQ6CBmSHELjpfTFNRpo4SyqfvPfCmh7DXnxEhKiNQN6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Build output configuration
[build]
incremental = true
out-dir = "target"

# Network-specific configurations
[test.validator]
url = "http://127.0.0.1:8899"
startup_wait = 10000

# RPC configurations
[rpc]
devnet = "https://api.devnet.solana.com"
mainnet = "https://api.mainnet-beta.solana.com"