[toolchain]
[features]
seeds = false
skip-lint = false

[test]
startup_wait = 10000


[programs.localnet]  
palm_presale = "EsySUN7oV4ayVueVak1QVWSibQSu3ePgqfKSEeCoxyTc"

[programs.devnet]  
palm_presale = "EsySUN7oV4ayVueVak1QVWSibQSu3ePgqfKSEeCoxyTc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"